### ISSUE TITLE
[PATCH] fix a typo

### ISSUE THREAD

**Issue by gregoa** [briandfoy/math-nocarry#1]
In Debian we are currently applying the following patch to
Math-NoCarry.
We thought you might be interested in it too.

```
Description: fix a typo
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2016-02-20
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libmath-nocarry-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by briandfoy** [comment]
Pull requests would be better :)

**Comment by kannix68** [comment]
Filed a pull request for this issue (typo in doc)
